enum ScreenNameEnum {
  //Auth Screens
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SIGNUP_SCREEN = 'SIGNUP_SCREEN',
  PASSWORD_RESET = 'PASSWORD_RESET',
 CREATE_PASSWORD = 'CREATE_PASSWORD',
  OTP_SCREEN = 'OTP_SCREEN',
  ASK_LOCATION ='ASK_LOCATION',
  LOCATION_SCREEN ='LOCATION_SCREEN',
  BOTTOM_TAB ='BOTTOM_TAB',

  // Tab Screens
  HOME_SCREEN='HOME_SCREEN',
  BOOKING_SCREEN = 'BOOKING_SCREEN',
  CART_STACK ='CART_STACK',
  PROFILE_STACK ='PROFILE_STACK',
  FAVORITE_SCREEN ='FAVORITE_SCREEN',
  PROFILE_SCREEN ='PROFILE_SCREEN',

//Features screen
RESTAURANT_DETAILS ='RESTAURANT_DETAILS',
REVIEW_SCREEN = 'REVIEW_SCREEN',
INFORMATION_SCREEN = 'INFORMATION_SCREEN',
DISH_INFORMATION = 'DISH_INFORMATION',
SEARCH_RESTAURANT ='SEARCH_RESTAURANT',
PAYMENT_SCREEN ='PAYMENT_SCREEN',
CART_SCREEN ='CART_SCREEN',
CATEGORY_DISHES ="CATEGORY_DISHES",
AllPopularDishes='AllPopularDishes',
MsgNotification='MsgNotification',
getTopRatedRestaurants='getTopRatedRestaurants',

//profile
MY_ORDER = 'MY_ORDER',
TRACK_ORDER ='TRACK_ORDER',
PAYMENT_CARD ='PAYMENT_CARD',
ADDNEW_CARD = 'ADDNEW_CARD',
EDIT_PROFILE ='EDIT_PROFILE',
TERMS_CONDITIONS ='TERMS_CONDITIONS',
PRIVACY_POLICY ='PRIVACY_POLICY',
CHANGE_PASSWORD ='CHANGE_PASSWORD',
ADDRESS_SCREEN ='ADDRESS_SCREEN',
NOTIFICATION_SCREEN='NOTIFICATION_SCREEN'



  
}

export default ScreenNameEnum;
